//
//  GlossaryChapter.swift
//  Cascade
//
//  Created by Pedro Wiezel on 16/02/26.
//

import SwiftUI

struct GlossaryChapter: View {
    var body: some View {
        VStack(alignment: .leading, spacing: 32) {

            TextParagraph("This is a quick reference guide for terms used throughout the simulation and the chapters.")

            VStack(alignment: .leading, spacing: 28) {

                GlossaryItem(
                    term: "Ablation",
                    definition: "The removal of material from the surface of an object by vaporization. In debris remediation, targeted lasers can ablate a debris surface to act as a miniature thruster."
                )

                GlossaryItem(
                    term: "Apogee & Perigee",
                    definition: "The highest (apogee) and lowest (perigee) points of an object's orbit around Earth. In the simulation, adjusting the 'Radial Spread' alters the apogee and perigee of the debris."
                )

                GlossaryItem(
                    term: "Atmospheric Drag",
                    definition: "The friction caused by collisions with sparse gas molecules in the upper atmosphere. It is the primary natural mechanism for removing orbital debris from low altitudes."
                )

                GlossaryItem(
                    term: "Conjunction",
                    definition: "A close approach between two objects in space. Space agencies track these events to determine if an operational satellite must perform an avoidance maneuver."
                )

                GlossaryItem(
                    term: "Criticality",
                    definition: "The tipping point in a Kessler Syndrome scenario where the rate of new debris generated by random collisions outpaces the rate at which old debris is cleared by atmospheric drag."
                )

                GlossaryItem(
                    term: "Geosynchronous Orbit (GEO)",
                    definition: "An orbital regime at 35,786 km where satellites match Earth's rotation, appearing to hover in a fixed spot in the sky. Objects travel much slower here than in LEO."
                )

                GlossaryItem(
                    term: "Graveyard Orbit",
                    definition: "A disposal orbit located roughly 300 km above Geosynchronous Orbit (GEO). Operators push dead satellites here to permanently remove them from highly congested operational lanes."
                )

                GlossaryItem(
                    term: "Hypervelocity",
                    definition: "Speeds typically exceeding 3 km/s (6,700 mph). In Low Earth Orbit, collision velocities often reach 10 to 15 km/s."
                )

                GlossaryItem(
                    term: "Inclination",
                    definition: "The tilt of an object's orbital plane relative to Earth's equator. In the simulation, spreading debris along the 'Normal' axis changes its inclination, throwing it into entirely new orbital planes."
                )

                GlossaryItem(
                    term: "Kinetic Energy",
                    definition: "The energy an object possesses due to its motion. It increases with the square of the velocity, which is why tiny orbital debris carries the explosive force of a hand grenade."
                )

                GlossaryItem(
                    term: "Low Earth Orbit (LEO)",
                    definition: "The region of space below 2,000 km in altitude. Because it is the easiest and cheapest orbit to reach, it is the most heavily congested and the primary focus of the Kessler Syndrome threat."
                )

                GlossaryItem(
                    term: "Mega-constellation",
                    definition: "A massive network of hundreds or thousands of satellites deployed to work together to provide global coverage, significantly increasing orbital density."
                )

                GlossaryItem(
                    term: "Space Surveillance Network (SSN)",
                    definition: "A worldwide network of radar and optical telescopes used to detect, track, catalog, and identify artificial objects orbiting Earth."
                )
            }
        }
    }
}
