import SwiftUI

struct MechanicsChapter: View {
    var body: some View {
        VStack(alignment: .leading, spacing: 40) {
            
            VStack(alignment: .leading, spacing: 24) {
                Text("The Cascade Effect")
                    .font(.title2.weight(.bold)).foregroundStyle(.white)
                
                TextParagraph("Kessler Syndrome is not a single event. It also doesn't happen as fast as it does in this simulation. It is a slow, self-reinforcing chain reaction that can take decades to reach criticality. We have been building up to it for 60 years. Recently, the buildup has accelerated.")
                
                CausalFlowDiagram()
                
                KeyConceptBox(
                    title: "What is Criticality?",
                    bodyText: "It is the tipping point where the rate of new debris generated by collisions outpaces the rate of old debris burning up in the atmosphere. Below 600 km, residual atmosphere clears fragments within years. Above 800 km, debris can persist for centuries.",
                    icon: "exclamationmark.arrow.circlepath"
                )
            }
            
            Divider().cascadeDivider()
            
            VStack(alignment: .leading, spacing: 24) {
                Text("Orbital Energy")
                    .font(.title2.weight(.bold)).foregroundStyle(.white)
                
                TextParagraph("Orbital collisions are catastrophic entirely because of speed. Objects in Low Earth Orbit travel at 7.5 km/s (about 27,000 km/h). At those speeds, even a paint fleck hits with the force of a bullet. A stray bolt carries the kinetic energy of a hand grenade.")
                
                ScientificCard {
                    VStack(alignment: .leading, spacing: 16) {
                        Label("KINETIC ENERGY EQUATION", systemImage: "function")
                            .font(.caption.weight(.bold))
                            .foregroundStyle(CascadeTheme.dimText)
                        
                        HStack(spacing: 4) {
                            Text("E")
                                .font(.title.weight(.semibold))
                                .foregroundStyle(.green)
                            Text("=")
                                .font(.title2)
                                .foregroundStyle(.white.opacity(0.6))
                            Text("½")
                                .font(.title)
                                .foregroundStyle(.white.opacity(0.8))
                            Text("m")
                                .font(.title.weight(.semibold))
                                .foregroundStyle(.blue)
                            Text("v²")
                                .font(.title.weight(.semibold))
                                .foregroundStyle(.orange)
                                .padding(.leading, -2)
                        }
                        .padding(.vertical, 8)
                        .frame(maxWidth: .infinity)
                        .accessibilityLabel("Kinetic energy equals one half times mass times velocity squared.")
                        
                        Text("Energy scales with the **square** of \(Text("velocity").foregroundStyle(.orange)). Doubling the speed of impact quadruples the \(Text("destructive power").foregroundStyle(.green)).")
                            .font(.subheadline)
                            .foregroundStyle(.secondary)
                            .lineSpacing(CascadeTheme.bodyLineSpacing)
                    }
                }
            }
            
            Divider().cascadeDivider()
            
            VStack(alignment: .leading, spacing: 24) {
                Text("Invisible Missiles")
                    .font(.title2.weight(.bold)).foregroundStyle(.white)
                
                TextParagraph("Space surveillance networks reliably track objects larger than 10 cm. However, fragments between 1 mm and 10 cm represent the most dangerous population. They are too small to track, but large enough to destroy a satellite.\n\nEvery bit of frozen coolant, metal shrapnel, or chipped paint becomes a hypervelocity missile. We estimate there are over 140 million of them in orbit right now.")
            
                HStack(spacing: 14) {
                    OperationalStatCard(
                        value: "~14,500",
                        unit: "satellites",
                        label: "active and operational as of 2026",
                        icon: "",
                        accent: .blue
                    )
                    
                    OperationalStatCard(
                        value: "> 55,000",
                        unit: "tracked",
                        label: "objects in orbit by Space Surveillance Networks",
                        icon: "",
                        accent: .yellow
                    )
                }
                
                HStack(spacing: 14) {
                    OperationalStatCard(
                        value: "1.2 million+",
                        unit: "non-tracked",
                        label: "objects estimated to be in orbit from 1 to 10cm",
                        icon: "",
                        accent: .orange
                    )
                    OperationalStatCard(
                        value: "140 million+",
                        unit: "non-tracked",
                        label: "objects estimated to be in orbit from 1mm to 1cm",
                        icon: "",
                        accent: .red
                    )
                }
            }
        }
    }
}

struct DebrisSizeClassView: View {
    var body: some View {
        VStack(alignment: .leading, spacing: 20) {
            Label("DEBRIS SIZE CLASSES", systemImage: "ruler.fill")
                .font(.caption.weight(.bold))
                .foregroundStyle(CascadeTheme.dimText)
            
            VStack(spacing: 14) {
                DebrisSizeRow(
                    size: "> 10 cm",
                    count: "~35,000", 
                    status: "Tracked",
                    statusColor: .green,
                    effect: "Catastrophic breakup",
                    proportion: 1.0
                )
                DebrisSizeRow(
                    size: "1 – 10 cm",
                    count: "~1.2 million", 
                    status: "Untracked", 
                    statusColor: .yellow,
                    effect: "Mission-ending damage",
                    proportion: 0.5
                )
                DebrisSizeRow(
                    size: "1 mm – 1 cm",
                    count: "~140 million", 
                    status: "Untracked",
                    statusColor: .red,
                    effect: "Degradation, destruction of fragile components",
                    proportion: 0.1 
                )
            }
        }
    }
}

struct DebrisSizeRow: View {
    let size: String
    let count: String
    let status: String
    let statusColor: Color
    let effect: String
    let proportion: Double
    
    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            HStack {
                Text(size)
                    .font(.subheadline.weight(.semibold))
                    .foregroundStyle(.white)
                
                Text("/")
                    .font(.caption.weight(.semibold))
                    .foregroundStyle(.white)
                
                Text(effect)
                    .font(.caption)
                    .foregroundStyle(CascadeTheme.mutedText)
                
                Spacer()
                
                Text(status)
                    .font(.caption2.weight(.bold))
                    .foregroundStyle(statusColor)
                    .padding(.horizontal, 8)
                    .padding(.vertical, 3)
                    .background(statusColor.opacity(CascadeTheme.iconBackgroundOpacity))
                    .clipShape(Capsule())
            }
            
            HStack(spacing: 16) {
                Text(count)
                    .font(.caption.weight(.bold).monospacedDigit())
                    .foregroundStyle(.white.opacity(0.7))
                    .frame(width: 100, alignment: .leading)
                
                Spacer()
            }
            
            GeometryReader { geo in
                ZStack(alignment: .leading) {
                    Capsule()
                        .fill(CascadeTheme.trackColor)
                        .frame(height: CascadeTheme.trackHeight)
                    
                    Capsule()
                        .fill(statusColor.opacity(0.6))
                        .frame(width: geo.size.width * proportion, height: CascadeTheme.trackHeight)
                }
            }
            .frame(height: CascadeTheme.trackHeight)
        }
        .padding(CascadeTheme.compactPadding)
        .background(CascadeTheme.cardBackground)
        .clipShape(RoundedRectangle(cornerRadius: 12))
        .accessibilityElement(children: .ignore)
        .accessibilityLabel("\(size): estimated \(count) objects, \(status). Effect: \(effect)")
    }
}

#Preview(traits: .landscapeLeft) {
    DebrisSizeClassView()
}
